### ISSUE TITLE
Is there a way to use TUN/TAP on Windows

### ISSUE THREAD

**Issue by dnx231** [ethack/docker-vpn#8]
hi,
is it possible to make a tun/tap connection thru the docker image under windows?

my connections working fine with openvpn and openconnect. i would like to route my packets from windows host to the appropriate networks without going through port-forwarding or socks proxy.

**Comment by ethack** [comment]
I don't have any experience with the tun/tap feature. It seems possible in Linux based on the SSH documentation. On Windows, I know there is at least one tun/tap driver you can install (ironically from OpenVPN) and so you might have luck with that. Or it might be usable through WSL2. Those are just my guesses as to what I would try first. 

At this point you might want to explore other options like customizing a native VPN install. If split routing is your concern you may want to look at the flags on OpenVPN that let you disable the routes pushed from the server and add your own. I'm not sure if these are available in the Windows build or not.
https://linux.die.net/man/8/openvpn#:~:text=using%20environmental%20variables.-,%2D%2Droute%2Dnopull,-When%20used%20with
