### ISSUE TITLE
OpenConnect config File

### ISSUE THREAD

**Issue by laruche** [ethack/docker-vpn#9]
Hi team ! 

Your work is impressive, and try to implement your solution on our local network for Devops Team ! 
Do you a sample file for openconnect ConfigFile (XML) 
I'm only have my local *.conf file

THanks

**Comment by ethack** [comment]
Sorry, I don't have an example openconnect file. I've only used command parameters for openconnect.

**Comment by laruche** [comment]
Hi,

I wrote a script with expect for that :)
